### PR TITLE
Fix incorrect month assignments

### PR DESCRIPTION
**Pull request by ajsmith27**
Just a small issue I noticed

### CODE REVIEW

**Comment by antonysmith-mando** [comment]
@DataJuggler I noticed your latest commit and the comment on it... The PR needs to be merged after it has been approved in order for it to update your code. Hope that helps.

**Comment by ajsmith27** [comment]
@DataJuggler I noticed your latest commit and the comment on it... The PR needs to be merged after it has been approved in order for it to update your code. Hope that helps.

**Comment by DataJuggler** [comment]
Ok. I have never done a pull request before.

Thanks

**Comment by ajsmith27** [comment]
Nor have I! I was excited about getting my first one merged and it didn’t even happen haha! I’ll have to find another issue to fix!

**Pull request merged**
